version: "3.8"
services:
  app-mysql:  # mysql服务
    image: mysql
    container_name: app-mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "/home/joneelmo/docker/mysql-es/conf:/etc/mysql/conf.d"
      - "/home/joneelmo/docker/mysql-es/data:/var/lib/mysql"
      - "/home/joneelmo/docker/mysql-es/log:/var/log/mysql"
    networks:
      - app-network
  app-redis:  # redis服务
    image: redis
    container_name: app-redis
    ports:
      - "6379:6379"
    volumes:
      # - "./server/redis/conf/redis.conf:/etc/redis/redis.conf"
      - "/home/joneelmo/A_mycode/gd_redis_data:/data"
    # command: redis-server /etc/redis/redis.conf
    networks:
      - app-network
    depends_on:
      - app-mysql
  app-java:  # java服务
    image: app
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app-java
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - app-mysql
      - app-redis
  app-nginx:  # nginx服务
    image: nginx
    container_name: app-nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - "/home/joneelmo/A_mycode/gdcode/deployTest/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/home/joneelmo/A_mycode/gdcode/deployTest/nginx/logs:/var/log/nginx"
      - "/home/joneelmo/A_mycode/gdcode/deployTest/nginx/html:/etc/nginx/html"
    networks:
      - app-network
    depends_on:
      - app-java
networks:
  app-network:
    name: app-network
