server:
  port:  8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jsoft_project03?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: redis
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis:
  configuration:
    map-underscore-to-camel-case: true
